atom-baseurl: /my-blog
encoding: UTF-8

markdown: rdiscount
highlighter: true
permalink: /:year/:month/:day/:title.html
name: "gaozhicheng's blog"
markdown: rdiscount

author: "gaozhicheng"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /my-blog/archive.html
  - title: Tags
    class: fa fa-tags
    href: /my-blog/tags.html
  - title: About
    class: fa fa-user
    href: /my-blog/about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Blogroll
    class: fa fa-link
    href: /my-blog/links.html
  - title: Subscribe
    class: fa fa-rss
    href: /my-blog/atom.xml
